//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Meseta.rc で使用
//
#define IDD_STATUS_3                    101
#define IDD_MESETA_DIALOG               102
#define IDD_PROPPAGE_HOTKEY             106
#define IDD_PROPPAGE_FUNCTION           107
#define IDD_PROPPAGE_DIRECTORY          108
#define IDD_PROPPAGE_MEDIUM             109
#define IDD_PROPPAGE_FONT               109
#define IDD_PROPPAGE_GAMEPAD            110
#define IDD_STATUS_1                    111
#define IDD_STATUS_2                    112
#define IDD_STATUS_4                    113
#define IDD_STATUS_6                    114
#define IDD_STATUS_5                    114
#define IDD_PROPPAGE_DISP               115
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_GAME_PAD             145
#define IDC_BUTTON_START                1000
#define IDC_LIST1                       1001
#define IDC_BUTTON_END                  1002
#define IDC_BUTTON_CONFIG               1003
#define IDC_STATIC_MPH                  1004
#define IDC_STATIC_MESETA1              1005
#define IDC_STATIC_MESETA2              1006
#define IDC_STATIC_MESETA3              1007
#define IDC_STATIC_INFO                 1008
#define IDC_EDIT_LOG_NGS                1009
#define IDC_STATIC_TIME                 1010
#define IDC_EDIT_SAVE_DIR               1011
#define IDC_SLIDER1                     1013
#define IDC_COMBO1                      1015
#define IDC_CHECK_PRE_ST                1020
#define IDC_CHECK_PRE_LOG               1021
#define IDC_CHECK_TRA_LOG               1022
#define IDC_CHECK_AUTO                  1023
#define IDC_HK_SHIFT                    1024
#define IDC_HK_CTRL                     1025
#define IDC_HK_ALT                      1026
#define IDC_COMBO_HOTKEY                1027
#define IDC_HK_WIN                      1028
#define IDC_BUTTON_LOG_NGS              1029
#define IDC_HK_SHIFT2                   1030
#define IDC_CHECK_AUTO_REFRESH          1031
#define IDC_HK_CTRL2                    1032
#define IDC_COMBO_AUTO_REFRESH          1033
#define IDC_HK_ALT2                     1034
#define IDC_CHECK_SAVE_POS              1035
#define IDC_HK_WIN2                     1036
#define IDC_EDIT_DIR_HELP               1037
#define IDC_COMBO_HOTKEY2               1038
#define IDC_PROP_CHECK_DEL_USE          1039
#define IDC_BUTTON_SAVE_DIR             1040
#define IDC_BUTTON_CHANGE_FONT          1041
#define IDC_PICTURE_BG                  1042
#define IDC_FONT_SAMPLE_1               1043
#define IDC_FONT_SAMPLE_2               1044
#define IDC_BUTTON_FONT_COL1            1045
#define IDC_BUTTON_FONT_COL2            1046
#define IDC_BUTTON_FONT_COL3            1047
#define IDC_EDIT_FONT                   1048
#define IDC_EDIT_FONT2                  1049
#define IDC_CHECK_PAD1                  1050
#define IDC_CHECK_PAD5                  1051
#define IDC_CHECK_PAD9                  1052
#define IDC_CHECK_PAD2                  1053
#define IDC_CHECK_PAD3                  1054
#define IDC_CHECK_PAD4                  1055
#define IDC_CHECK_PAD6                  1056
#define IDC_CHECK_PAD7                  1057
#define IDC_CHECK_PAD8                  1058
#define IDC_CHECK_PAD10                 1059
#define IDC_CHECK_PAD11                 1060
#define IDC_CHECK_PAD12                 1061
#define IDC_CHECK_PAD13                 1062
#define IDC_CHECK_PAD14                 1063
#define IDC_CHECK_PAD15                 1064
#define IDC_CHECK_PAD16                 1065
#define IDC_CHECK_PAD17                 1066
#define IDC_CHECK_PAD18                 1067
#define IDC_CHECK_PAD19                 1068
#define IDC_CHECK_PAD20                 1069
#define IDC_CHECK_PAD21                 1070
#define IDC_CHECK_PAD22                 1071
#define IDC_CHECK_PAD23                 1072
#define IDC_CHECK_PAD24                 1073
#define IDC_CHECK_PAD25                 1074
#define IDC_CHECK_PAD26                 1075
#define IDC_CHECK_PAD27                 1076
#define IDC_CHECK_PAD28                 1077
#define IDC_CHECKGAMEPAD_USE            1078
#define IDC_COMBO_GAMEPAD_ID            1079
#define IDC_STATIC_PADID                1080
#define IDC_EDIT_PAD_CONNECT            1081
#define IDC_EDIT_PAD_TEST               1082
#define IDC_STATIC_MESETA4              1083
#define IDC_STATIC_MESETA5              1084
#define IDC_COMBO_LOG_NUM               1085
#define IDC_COMBO_SUB_DATA              1086

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
